### ISSUE TITLE
评论中的视频爬取不了

### ISSUE THREAD

**Issue by zhegeshijiehuiyouai** [zhengxiangyue/pipix#1]
获取到评论中的视频链接后，用浏览器打开看到的是评论中的视频，但是用脚本爬下来，始终是这个评论所在的帖子的视频

**Comment by zhengxiangyue** [comment]
> 获取到评论中的视频链接后，用浏览器打开看到的是评论中的视频，但是用脚本爬下来，始终是这个评论所在的帖子的视频

@zhegeshijiehuiyouai 难受哈哈哈，看了一眼，评论里面的视频都是加了水印之后再暴露给客户端的，也就是没有原视频的地址，或者说原视频就是已经加过水印的，和直接下载有水印的效果一样。

**Comment by zhegeshijiehuiyouai** [comment]
给跪了
